# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfLabelsFileLocation', models.CharField(max_length=500)),
                ('tfGraphFileLocation', models.CharField(max_length=500)),
                ('tfNNeckDirectory', models.CharField(max_length=500)),
                ('tfModelDirectory', models.CharField(max_length=500)),
                ('tfMaxScore', models.IntegerField()),
                ('tfMaxSteps', models.IntegerField()),
                ('tfScriptLocation', models.CharField(max_length=500)),
            ],
        ),
    ]
