# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tflow',
            name='tfImagesDirectory',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
