# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('native', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identityCover', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now=True, db_index=True)),
                ('identityNative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='native.Native')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=250)),
                ('imageSize', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now=True, db_index=True)),
                ('imageIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.Identity')),
            ],
        ),
        migrations.CreateModel(
            name='SmsIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsNumber', models.CharField(max_length=20)),
                ('smsText', models.CharField(max_length=40)),
                ('createdAt', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.BooleanField(default=True)),
                ('identityNative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='native.Native')),
            ],
        ),
    ]
