# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_identityimage_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityimage',
            name='imageSize',
            field=models.IntegerField(default=0),
        ),
    ]
