# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('native', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guessValue', models.IntegerField(default=0)),
                ('guessLabel', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageRecognizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageLocation', models.FileField(upload_to='media/')),
                ('imageName', models.CharField(max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessfullPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now=True, db_index=True)),
                ('guessId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.Guess')),
                ('imageRecognizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.ImageRecognizer')),
                ('nativeIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='native.Native')),
            ],
        ),
        migrations.AddField(
            model_name='guess',
            name='imageRecognizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.ImageRecognizer'),
        ),
    ]
