# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('sms', models.CharField(max_length=40)),
                ('createdAt', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessfullSmsPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now=True, db_index=True)),
                ('smsIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.SmsIdentity')),
                ('smsRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.SmsRequest')),
            ],
        ),
    ]
