# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_auto_20170223_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guess',
            name='imageRecognizer',
        ),
        migrations.AddField(
            model_name='guess',
            name='wasGuess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recognizerimage',
            name='guess',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recognition.Guess'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recognizerimage',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recognizerimage',
            name='wasSuccess',
            field=models.BooleanField(default=False),
        ),
    ]
