# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0004_auto_20170225_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognizerimage',
            name='guess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recognition.Guess'),
        ),
    ]
