# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0005_auto_20170225_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsrequest',
            name='isBlocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smsrequest',
            name='wasSuccess',
            field=models.BooleanField(default=False),
        ),
    ]
