# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0007_smsrequest_smsidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsrequest',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
    ]
