# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Native',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('nativeName', models.CharField(max_length=40)),
                ('nativeStatus', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
