# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.CharField(max_length=10)),
                ('endTime', models.CharField(max_length=10)),
                ('native', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='native.Native')),
            ],
        ),
    ]
